const fs = require('fs');

function patch() {
  let appCode = fs.readFileSync('src/App.tsx', 'utf8');

  const pStart = appCode.indexOf("const handleCreateFirePreset = useCallback(async (presetType: 'campfire' | 'torch') => {");
  if (pStart === -1) {
      console.log('Cannot find preset start.');
      return;
  }
  const pEnd = appCode.indexOf('// Physics forces', pStart);

  let customCode = appCode.substring(pStart, pEnd);

  // Eliminate wind and physics because these fire sequences have THEIR OWN MOVEMENT generated by shader
  appCode = appCode.replace('setPhysicsForces((prev) => [...prev, windForce, turbulenceForce]);', '/* setPhysicsForces((prev) => [...prev, windForce, turbulenceForce]); */');
  
  // Actually, wait, let's redefine the emitter to not drift around.
  customCode = customCode.replace(
    "particleSpeed: presetType === 'campfire' ? 20 : 60,",
    "particleSpeed: dataUrls.length > 0 ? 0 : (presetType === 'campfire' ? 20 : 60),"
  );
  
  // We should also remove rotation variation since it's a fixed up-oriented flame sequence
  customCode = customCode.replace(
    "particleRotationVariation: 180,",
    "particleRotationVariation: dataUrls.length > 0 ? 0 : 180,"
  );
  
  customCode = customCode.replace(
    "particleRotationSpeed: 2,",
    "particleRotationSpeed: dataUrls.length > 0 ? 0 : 2,"
  );
  
  customCode = customCode.replace(
    "particleRotationSpeedVariation: 1,",
    "particleRotationSpeedVariation: dataUrls.length > 0 ? 0 : 1,"
  );
  
  // Reduce size variation so it doesn't look messy
  customCode = customCode.replace(
    "particleSizeVariation: 0.4,",
    "particleSizeVariation: dataUrls.length > 0 ? 0.05 : 0.4,"
  );
  
  // For small budgets, the rate is fine, but they should spawn perfectly to overlap without gaps
  customCode = customCode.replace(
    "emissionRate: dataUrls.length > 0 ? (presetType === 'campfire' ? 5 : 10) : (presetType === 'campfire' ? 150 : 250),",
    "emissionRate: dataUrls.length > 0 ? (presetType === 'campfire' ? 15 : 20) : (presetType === 'campfire' ? 150 : 250),"
  );
  
  // The particles shouldn't move! The animation provides the shape.
  // We'll also just change emitterType to 'point' or very small 'circle'
  customCode = customCode.replace(
    "emitterType: 'circle',",
    "emitterType: dataUrls.length > 0 ? 'point' : 'circle',"
  );
  
  appCode = appCode.substring(0, pStart) + customCode + appCode.substring(pEnd);
  
  fs.writeFileSync('src/App.tsx', appCode);
  console.log('App patched physics & speeds properly.');
}

patch();